### ISSUE TITLE
youtube api not working

### ISSUE THREAD

**Issue by skgupta507** [onamkrverma/okv-music#19]
hello @onamkrverma the api from youtube is not working it gives json error unexpected error
tried using a alternative youtube api from rapid api but that also is not working.
can u suggest a repo for the api or can u share the link for the api.so that we can use in our projects.
i tries hosting it several times with different api but its not working. your help will be appreciated kindly guide me with the solution.
or do i ned to make any chnages to the code to make it work with other apis

**Comment by onamkrverma** [comment]
Guide to use YouTube API 
https://developers.google.com/youtube/v3/getting-started 

> If you can share your project repository then it could be easy to understand the real issue, why YouTube API is not working for you.

**Comment by skgupta507** [comment]
Hey @onamkrverma i have added u as a collaborator as my repo is private. pls look into it and help me solve the issue

**Comment by skgupta507** [comment]
Hello @onamkrverma thanks for the assist but can u share the source code of the api u implemented in the code.
thanks to ur help the error was solved.
i have some projects similar to this are u interested in collaborating in its development. i have sent a request on ur linkedin profile hope to listen back soon.
