### ISSUE TITLE
up next songs not showing

### ISSUE THREAD

**Issue by skgupta507** [onamkrverma/okv-music#20]
hello @onamkrverma the upnext page is not showing in my hosted site so the autoplay is not working.
the player stops after playing one song. how to fix the error or  issue

**Comment by skgupta507** [comment]
hey bro its not yet fixed can u fix it for us

**Comment by onamkrverma** [comment]
This feature is working on okv-music. You need to setup you backend to get related song list.
Use this [Ytdl-core](https://github.com/fent/node-ytdl-core#readme) package on your backend to get related songs list. Fetch this list on frontend side and setup next and previous button to change current playing song.
